Start a minimal CNS implementation.
dfinity/cns pull request #66
Opened 2024-11-27 11:40 UTC by przydatek

Start an implementation of a minimal CNS.  This PR adds a very minimal CNS root canister with basic tests.

2024-11-27 15:10 UTC, nathanosdev submitted a review, later dismissed

2024-11-27 15:10 UTC, nathanosdev commented on dfx.json
> +{
It would be useful to add the DFX version here:
```suggestion
{
  "dfx": "0.24.2",
```

2024-11-27 15:10 UTC, nathanosdev commented on dfx.json
> +  },
Just to clean up some unnecessary stuff:
```suggestion
```

2024-11-27 15:10 UTC, nathanosdev commented on minimal_cns/README.md
> +  dfx deploy cns_root_test
`dfx deploy` is enough to create and deploy all canisters listed in the `dfx.json` file

```suggestion
  dfx deploy
```

2024-11-27 15:10 UTC, nathanosdev commented on minimal_cns/src/backend/cns_root.mo
> +shared ({ caller = initializer }) actor class () {
Seems to not be used?
```suggestion
shared actor class () {
```

2024-11-27 15:10 UTC, nathanosdev commented on minimal_cns/src/backend/cns_root.test.mo
> +    };
Should we also add a test for the case where record type is not `NC`?

2024-11-27 15:22 UTC, przydatek reviewed
Thanks!

2024-11-27 15:22 UTC, przydatek commented on minimal_cns/README.md
> +  dfx deploy cns_root_test
just `dfx deploy` doesn't work currently as `name_registry` canister doesn't build properly, hence the step-by-step deployment.

2024-11-27 15:22 UTC, przydatek commented on minimal_cns/src/backend/cns_root.test.mo
> +    };
There is `"NS"` in the third example, although admittedly it combined there with a non-`.icp` domain.  I'll add another example when adding testing to CI.

2024-11-27 15:22 UTC, przydatek commented on minimal_cns/src/backend/cns_root.mo
> +shared ({ caller = initializer }) actor class () {
Indeed!

2024-11-27 15:22 UTC, przydatek commented on dfx.json
> +  },
Thanks!

2024-11-28 09:29 UTC, nathanosdev approved these changes

2024-11-29 09:29 UTC, keplervital requested changes

2024-11-29 09:29 UTC, keplervital commented on minimal_cns/src/backend/cns_root.mo
> +            authorities = [];
This won't work because client's won't request for the `NC` record type directly,a typical query will request for the target record type and domain directly e.g. `lookup("example.icp.", "CID")`, this is what the cns root will receive, and since it does not handle this value, it should return the answers section as empty and the authorities section should include the NC record with the `icp_tld_canister_id`, then the client can query that authorities canister to request for the "CID" record of "example.icp."

2024-11-29 09:29 UTC, keplervital commented on minimal_cns/src/backend/cns_root.test.mo
> +    func shouldGetIcpTldOperator() : async () {
let's test both requesting for the NC record directly to make sure it is included in the answer section and for another record type to make sure NC is included in the authorities section

2024-11-29 10:49 UTC, keplervital commented on minimal_cns/src/backend/cns_root.mo
> +                case ("CID") {
we don't need to check for `CID`, the default case can be to return the `NC` record for authorities

2024-11-29 11:00 UTC, przydatek commented on minimal_cns/src/backend/cns_root.mo
> +                case ("CID") {
Done.

2024-11-29 11:00 UTC, przydatek commented
Thanks, PTAL.

2024-11-29 11:06 UTC, keplervital approved these changes

2024-11-29 11:07 UTC, merged